### ISSUE TITLE
metadata.cc doesn't build (exif 0.25 & 0.27)

### ISSUE THREAD

**Issue by agriggio** [artpixls/ART#55]
**[Original report](https://bitbucket.org/agriggio/art/issues/55) by David Hunt (Bitbucket: [David Hunt](https://bitbucket.org/David Hunt), ).**

----------------------------------------

I’ve struggled to get [metadata.cc](http://metadata.cc) to compile and get a bunch of errors

‌

```c++
metadata.cc:72:15: error: ‘AutoPtr’ in ‘class Exiv2::Image’ does not name a type
   72 | Exiv2::Image::AutoPtr open_exiv2(const Glib::ustring &fname)
      |               ^~~~~~~
metadata.cc:279:15: error: ‘AutoPtr’ in ‘class Exiv2::Image’ does not name a type
  279 | Exiv2::Image::AutoPtr exiftool_import(const Glib::ustring &fname, const std::exception &exc)
      |               ^~~~~~~
...
```

I’m not sure how others are getting it to compile. I’ve changed the code from using AutoPtr to using std unique\_ptr’s \(which I believe is what exif 0.28 is going to be using\) and now it builds fine for me \(on exif 0.27\).

Let me know what you think of this change.

**Comment by agriggio** [comment]
**Original comment by agriggio (Bitbucket: [agriggio](https://bitbucket.org/agriggio), GitHub: [agriggio](https://github.com/agriggio)).**

----------------------------------------

hi,

thanks for reporting. I build with 0.27.2 and never got any problem. however, I'll make sure art is ready for 0.28

**Comment by agriggio** [comment]
**Original comment by agriggio (Bitbucket: [agriggio](https://bitbucket.org/agriggio), GitHub: [agriggio](https://github.com/agriggio)).**

----------------------------------------

metadata: use std::unique_ptr instead of Exiv2::Image::AutoPtr

Fixes #55
